print("ENTER NUMBERS FOR THE LIST (SEPARATED BY SPACE) : ")
m = input().split()
num = input("ENTER THE VALUE TO BE REMOVED FROM THE DISPLAYED LIST :")
my_list = list(filter(lambda x: x != num, m))
print("THE FINAL LIST IS : ", my_list)
